package:
  name: wallflower
  version: 0.2

source:
  path: .


requirements:
  build:
    - python
    - setuptools
    - numpy 1.17.3
    - scipy >=1.3.1

  run:
    - python
    - numpy 1.17.3
    - scipy >=1.3.1

about:
  home: https://github.com/khirotaka/wallflower
  license: MIT
  description : |
